# Generated by Django 5.2.7 on 2026-06-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_episode_code_oj_enabled_episode_code_oj_testcases'),
        ('progress', '0003_quizsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, help_text='Submitted Python code')),
                ('test_results', models.TextField(blank=True, default='[]', help_text='JSON: [{passed, input, expected, actual, error}] per test case')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='courses.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Code Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
