# Generated by Django 5.2.7 on 2026-07-26

from django.db import migrations, models
from django.utils import timezone


def mark_existing_records_submitted(apps, schema_editor):
    CodeSubmission = apps.get_model('progress', 'CodeSubmission')
    CodeSubmission.objects.update(is_submitted=True)


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='is_submitted',
            field=models.BooleanField(
                default=False,
                help_text='Whether the student has formally submitted this upload',
            ),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_records_submitted,
            migrations.RunPython.noop,
        ),
    ]
