# Generated by Django 5.2.7 on 2026-09-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_codesubmission_upload_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at', '-uploaded_at'], 'verbose_name_plural': 'Code Submissions'},
        ),
    ]
