# Generated by Django 5.2.7 on 2026-09-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def copy_existing_submissions(apps, schema_editor):
    CodeSubmission = apps.get_model('progress', 'CodeSubmission')
    CodeSubmissionHistory = apps.get_model('progress', 'CodeSubmissionHistory')
    for submission in CodeSubmission.objects.filter(is_submitted=True).iterator():
        submitted_at = submission.submitted_at or submission.uploaded_at or timezone.now()
        snapshot = CodeSubmissionHistory.objects.create(
            user_id=submission.user_id,
            episode_id=submission.episode_id,
            code=submission.code,
            test_results=submission.test_results,
        )
        CodeSubmissionHistory.objects.filter(pk=snapshot.pk).update(
            submitted_at=submitted_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_alter_codesubmission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, help_text='Submitted Python code snapshot')),
                ('test_results', models.TextField(blank=True, default='[]', help_text='JSON test-result snapshot from formal submission')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submission_history', to='courses.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submission_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Code Submission History',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.RunPython(
            code=copy_existing_submissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
