# Generated by Django 5.2.7 on 2025-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_alter_episode_options_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal bio or introduction', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name shown to other users', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='6-digit verification code', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When verification code was sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, help_text='User preferred tags', related_name='favorited_by', to='courses.tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether email has been verified'),
        ),
    ]
