# Generated by Django 5.2.7 on 2026-05-25 11:13

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_episode_options_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='answer_pdf',
            field=models.FileField(blank=True, help_text='Answer PDF (for quiz and paper types)', null=True, upload_to=courses.models.answer_pdf_path),
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('material', 'Material'), ('quiz', 'Quiz'), ('code', 'Code'), ('paper', 'Paper')], max_length=10),
        ),
    ]
