# Generated by Django 5.2.7 on 2026-05-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_episode_answer_pdf_alter_episode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='show_interactive',
            field=models.BooleanField(default=True, help_text='Show the Interactive panel in code episodes'),
        ),
        migrations.AddField(
            model_name='episode',
            name='show_reference',
            field=models.BooleanField(default=True, help_text='Show the Reference panel in code episodes'),
        ),
    ]
