# Generated by Django 5.2.7 on 2026-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_episode_show_interactive_episode_show_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='8-character code for students to enroll (auto-generated)', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_mode',
            field=models.CharField(choices=[('open', 'Open to all'), ('code', 'Require code')], default='code', help_text='How students join this course', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_open',
            field=models.BooleanField(default=True, help_text='Whether new enrollments are currently accepted'),
        ),
    ]
