# Generated by Django 5.2.7 on 2026-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_episode_quiz_require_all_episode_quiz_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='code_oj_enabled',
            field=models.BooleanField(default=False, help_text='Enable OJ mode with test cases for code episodes'),
        ),
        migrations.AddField(
            model_name='episode',
            name='code_oj_testcases',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of {input, expected_output} test case pairs'),
        ),
    ]
