# Generated by Django 5.2.7 on 2026-06-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_episode_code_oj_enabled_episode_code_oj_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='reference_sheet_content',
            field=models.TextField(blank=True, default='', help_text='Markdown reference sheet for code episodes'),
        ),
    ]
