# Generated by Django 5.2.7 on 2026-07-26

from django.db import migrations, models


def migrate_immediate_release_episodes(apps, schema_editor):
    Episode = apps.get_model('courses', 'Episode')
    Episode.objects.filter(quiz_show_results=True).update(
        quiz_release_policy='immediate'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_episode_reference_sheet_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='quiz_release_policy',
            field=models.CharField(
                choices=[
                    ('inherit', 'Use course default'),
                    ('manual', 'Require teacher release'),
                    ('immediate', 'Release immediately'),
                ],
                default='inherit',
                help_text='Whether this quiz inherits the course default, requires review, or releases immediately',
                max_length=10,
            ),
        ),
        migrations.RunPython(
            migrate_immediate_release_episodes,
            migrations.RunPython.noop,
        ),
    ]
