# Generated by Django 5.2.7 on 2026-09-07

from django.db import migrations, models


DEFAULT_STARTER_CODE = '# Write your Python code here\n'


def populate_code_episode_starter_code(apps, schema_editor):
    Episode = apps.get_model('courses', 'Episode')
    Episode.objects.filter(type='code', starter_code='').update(
        starter_code=DEFAULT_STARTER_CODE
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_episode_quiz_release_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='starter_code',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Initial Python code shown to students before they save or upload work',
            ),
        ),
        migrations.RunPython(
            populate_code_episode_starter_code,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='episode',
            name='starter_code',
            field=models.TextField(
                blank=True,
                default=DEFAULT_STARTER_CODE,
                help_text='Initial Python code shown to students before they save or upload work',
            ),
        ),
    ]
