# Generated by Django 5.2.7 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_episode_starter_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='quiz_show_results',
            field=models.BooleanField(
                default=False,
                help_text='Legacy release setting; migrated to quiz_release_policy',
            ),
        ),
    ]
