# Generated by Django 5.2.7 on 2026-09-07 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_creator_manager_memberships(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseTeacherMembership = apps.get_model('courses', 'CourseTeacherMembership')
    CourseTeacherMembership.objects.bulk_create([
        CourseTeacherMembership(course_id=course.id, user_id=course.creator_id, role='manage')
        for course in Course.objects.exclude(creator_id=None).iterator()
    ], ignore_conflicts=True)


def remove_creator_manager_memberships(apps, schema_editor):
    # Memberships may have been changed by users after migration, so never
    # remove them during a reverse migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_section_options_and_quiz_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacherMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('view', 'View student work'), ('edit', 'Edit course content'), ('manage', 'Manage course')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_memberships', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_id', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='unique_course_teacher_membership')],
            },
        ),
        migrations.RunPython(
            add_creator_manager_memberships,
            remove_creator_manager_memberships,
        ),
    ]
