# Generated by Django 5.2.7 on 2026-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='counts_toward_progress',
            field=models.BooleanField(default=True, help_text='Include this episode in course progress calculations'),
        ),
    ]
