"""
Django settings for ts_courser project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Version
VERSION = '1.0.0-rc'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Local development fallback only. Production uses settings_production.py and
# refuses to start unless DJANGO_SECRET_KEY is supplied.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'dev-only-key-change-me-before-deploying',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'accounts',
    'courses',
    'progress',
    'teacher',
]

MIDDLEWARE = [
    'ts_courser.middleware.CrossOriginIsolationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ts_courser.middleware.AccountStateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ts_courser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'ts_courser.context_processors.version_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ts_courser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'node_modules' / 'monaco-editor' / 'min',
    BASE_DIR / 'node_modules' / 'pyodide',
    (
        'vendor/webgl-fluid',
        BASE_DIR / 'node_modules' / 'webgl-fluid' / 'dist',
    ),
]

# Media files (User uploads)
MEDIA_URL = 'protected-media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.LocalAccountBackend',
    'accounts.backends.EntraSessionBackend',
]

# Login/Logout redirects
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'courses:course_list'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Microsoft Entra ID (global cloud, single school tenant). Tenant/client IDs and
# the callback are public identifiers; the client secret must only come from the
# deployment environment.
MS_ENTRA_TENANT_ID = os.environ.get(
    'MS_ENTRA_TENANT_ID',
    '7222912a-435d-423b-b22b-74b909c3bf8b',
).strip()
MS_ENTRA_CLIENT_ID = os.environ.get(
    'MS_ENTRA_CLIENT_ID',
    '5910709e-99db-4cc0-9468-88497aa32f23',
).strip()
MS_ENTRA_CLIENT_SECRET = os.environ.get('MS_ENTRA_CLIENT_SECRET', '').strip()
MS_ENTRA_REDIRECT_URI = os.environ.get(
    'MS_ENTRA_REDIRECT_URI',
    'https://courser.tsinglan.top/accounts/microsoft/callback/',
).strip()
MS_ENTRA_AUTHORITY = f'https://login.microsoftonline.com/{MS_ENTRA_TENANT_ID}'
MS_ENTRA_ENABLED = bool(
    MS_ENTRA_TENANT_ID and MS_ENTRA_CLIENT_ID and MS_ENTRA_CLIENT_SECRET
)

LOCAL_INITIAL_PASSWORD_TTL_DAYS = int(
    os.environ.get('LOCAL_INITIAL_PASSWORD_TTL_DAYS', '7')
)
